In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

##  IMPORT LIBRARIES

In [ ]:
pip install --upgrade scipy

In [ ]:
import pandas as pd                # for data manipulation and analysis
import numpy as np                 # for numerical computing
import matplotlib.pyplot as plt    # for data visualization
import seaborn as sns              # for advanced data visualization
import plotly.express as px
import plotly.graph_objects as go # FOR graph ploting

In [ ]:
df = pd.read_csv('/kaggle/input/indian-restaurants-2023/restaurants.csv')

In [ ]:
df.head(15)

In [ ]:
df.columns

# CHECK ALL NULL VALUES

In [ ]:
print(df.isnull().sum())

### OBSERVATION
#### AFTER THE EXPOLORING THE DATA SET, ITS OBSERVATION THAT THERE IS NO NULL VALUES IN PRESENT THE COLUMNS:

#### Name
#### Location
#### Locality
#### City
#### Cuisine
#### Rating
#### Votes
#### Cost

In [ ]:
df.describe()

In [ ]:
df.info()

# COUNT CITY

In [ ]:
df['City'].value_counts()

In [ ]:
df['State'] = df['City']
df['State'] = df['City'].replace({'Bangalore': 'Karnataka','Delhi':'Delhi NCR', 'Mumbai': 'Maharashtra', 'Kolkata': 'Bengal',
'Hyderabad': 'Telangana','Ahmedabad': 'Gujrat','Chennai' : 'Tamil Nadu','Pune' : 'Maharashtra','Jaipur' : 'Rajasthan',
'Chandigarh' : 'Punjab','Indore' : 'Madhya Pradesh','Gurgaon' : 'Delhi NCR','Noida' : 'Delhi NCR','Vadodara' : 'Gujrat',
'Lucknow' : 'Uttar Pradesh','Agra' : 'Uttar Pradesh','Nagpur' : 'Maharashtra','Surat' : 'Gujrat','Ludhiana' : 'Punjab',
'Goa' : 'Goa','Ghaziabad' : 'Delhi NCR','Udaipur' : 'Rajasthan','Kochi' : 'Kerala'})

df['State'].value_counts()

In [ ]:
df

#### A new column named "State"
#### has been added to the dataset by merging the cities state-wise. This column will help us in further analysis by providing insights based on the states in which the restaurants are located.

# DATA VISUALISATION

In [ ]:
# Rating distribution
plt.figure(figsize=(8,6))
plt.hist(df['Rating'], bins=20, color='green')
plt.title('Distribution of Restaurant Ratings in India')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

# Cost distribution
plt.figure(figsize=(8,6))
plt.hist(df['Cost'], bins=20, color='blue')
plt.title('Distribution of Restaurant Costs in India')
plt.xlabel('Cost')
plt.ylabel('Count')
plt.show()

# Votes distribution
plt.figure(figsize=(8,6))
plt.hist(df['Votes'], bins=20, color='orange')
plt.title('Distribution of Restaurant Votes in India')
plt.xlabel('Votes')
plt.ylabel('Count')
plt.show()

### Distribution of Restaurants across Cities in India

In [ ]:
plt.figure(figsize=(15,8))
sns.countplot(y = 'City', data = df, order = df['City'].value_counts().index, palette = 'viridis')
plt.title('Distribution of Restaurants across Cities in India')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.show()

In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame and 'State' is a column in it
df_state = df.groupby('State').mean(numeric_only=True)  # Explicitly set numeric_only to True

In [ ]:
# Forming state-wise dataframe
df_state = df.groupby('State').mean()
df_state.reset_index(level = 0, inplace = True)
df_state

# RATING DISTRIBUTION ACROSS STATES

In [ ]:
# Forming state-wise dataframe
df_state = df.groupby('State').mean()
df_state.reset_index(level = 0, inplace = True)

# Plotting the state-wise rating distribution
plt.figure(figsize=(15,8))
sns.barplot(x='State', y='Rating', data=df_state, palette='YlOrBr')
plt.title('Rating Distribution Across States', fontsize=20)
plt.xlabel('State', fontsize=15)
plt.ylabel('Average Rating', fontsize=15)
plt.xticks(rotation=90, fontsize=12)
plt.yticks(fontsize=12)
plt.show()

# OBSERVATION

#### COMPARISION OF RATING ACROSS STATES

In [ ]:
fig = px.bar(df_state, x='State', y='Rating', color='State', 
             title='Comparison of Ratings Across States',
             labels={'State':'State', 'Rating':'Average Rating'})
fig.show()

### Comparison of Average Dining Cost Across States

In [ ]:
# create a dataframe with average cost by state
df_cost = df.groupby('State')['Cost'].mean().reset_index()

# sort the dataframe by cost
df_cost = df_cost.sort_values('Cost')

# set color palette
colors = ['red','blue','yellow','pink','green','black','purple','gray','#00ACC1','#4FC3F7','#9575CD','#E57373','#F06292','#BA68C8','#F48FB1','#BDBDBD','#90A4AE','#80DEEA','#FFD54F','#F44336']

# plot the data as a horizontal bar chart
plt.figure(figsize=(10, 8))
plt.barh(df_cost['State'], df_cost['Cost'], color=colors)
plt.title('Comparison of Average Dining Cost Across States')
plt.xlabel('Average Cost (in Indian Rupees)')
plt.ylabel('State')

# add value labels to the bars
for index, value in enumerate(df_cost['Cost']):
    plt.text(value, index, str(round(value,2)), color='black', fontsize=10, ha='left', va='center')

plt.show()

# Comparison of Average Dining Cost Across Cities

In [ ]:
# create a dataframe with average cost by city
df_cost_city = df.groupby('City')['Cost'].mean().reset_index()

# sort the dataframe by cost
df_cost_city = df_cost_city.sort_values('Cost')

# plot the data as a horizontal bar chart
plt.figure(figsize=(12, 8))
plt.barh(df_cost_city['City'], df_cost_city['Cost'], color='purple')
plt.title('Comparison of Average Dining Cost Across Cities', fontsize=18)
plt.xlabel('Average Cost (in Indian Rupees)', fontsize=14)
plt.ylabel('City', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# comparison od average rating across states

In [ ]:
# create a dataframe with average rating by state
df_rating = df.groupby('State')['Rating'].mean().reset_index()

# sort the dataframe by rating
df_rating = df_rating.sort_values('Rating')

# create a pie chart
plt.figure(figsize=(8,8))
plt.pie(df_rating['Rating'], labels=df_rating['State'], autopct='%2.2f%%', startangle=90, explode=[0.1]*len(df_rating))
plt.title('Comparison of Average Ratings Across States')
plt.show()

# state wise distribution

In [ ]:
df_state

In [ ]:
# group the data by state and sum the votes
df_votes = df_state.groupby('State')['Votes'].sum().reset_index()

# create the pie chart
fig = go.Figure(data=[go.Pie(
    labels=df_votes['State'],
    values=df_votes['Votes'],
    textinfo='value+percent',
    hole=.4,
    sort=False,
    marker=dict(colors=px.colors.qualitative.Dark2))
])

# add title and customize layout
fig.update_layout(title='Votes Distribution Across States',
                  title_x=0.5,
                  annotations=[dict(text='Votes', font_size=30, showarrow=False)],
                  showlegend=False)

fig.show()

# Top cuisines in India

In [ ]:
# group the data by city and cuisine and count the number of restaurants
df_cuisine = df.groupby(['City', 'Cuisine'])['Name'].count().reset_index()

# get the top cuisine for each city
df_top_cuisine = df_cuisine.loc[df_cuisine.groupby('City')['Name'].idxmax()]

# create the bar chart
fig = px.bar(df_top_cuisine, x='City', y='Name', color='Cuisine',
             labels={'City': 'City', 'Name': 'Number of Restaurants'},
             title='Top Cuisine in Each City')
fig.show()

a description of the EDA
Okay, so in our EDA on Indian restaurants, we took the following actions:
After loading the relevant libraries, we imported the dataset. Then, if any null values were discovered, we addressed them.

We looked at the basic statistics of the dataset and visualised the distribution of the variables. The relationships between the various variables were also looked at.

We used the analysis' results to rank the top restaurants and geographical areas. We also looked at the distribution of restaurants across Indian states and cities.

The votes, ratings, and meal prices from various states and cities were then compared. We also took into account the top eateries in India.
Overall, we have run numerous analyses on this dataset, even while